=== lvisintini/imperial-assault-data/schemas/campaign-ally-side-missions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "campaign-ally-side-missions.json#",
  "title": "Schema for the campaign ally side missions data file (green side missions; the allies they give are in mission-rewards)",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "description": "Id for entry: a UUID (see docs/data-model.md).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "name": {
      "type": "string",
      "description": "Ally side mission name",
      "minLength": 1
    },
    "back_id": {
      "description": "Foreign key to this card's back in data/card-backs.json.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "image": {
      "description": "The file path for this ally side mission's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    }
  },
  "required": [
    "id",
    "name",
    "back_id",
    "image"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/form-cards.json
[
  {
    "id": "804d06a0-f6c4-5077-b593-73a26d343fc3",
    "name": "Streetrat",
    "back_id": "0e5996f5-f324-5113-b524-69741c8f2dfb",
    "image": "form-cards/clawdite-shapeshifter-streetrat.png"
  },
  {
    "id": "23b3259f-1471-59df-a77d-4a2c5c616de3",
    "name": "Senator",
    "back_id": "0e5996f5-f324-5113-b524-69741c8f2dfb",
    "image": "form-cards/clawdite-shapeshifter-senator.png"
  },
  {
    "id": "d4002aa2-fc90-515d-9267-57479ae9ad3b",
    "name": "Scout",
    "back_id": "0e5996f5-f324-5113-b524-69741c8f2dfb",
    "image": "form-cards/clawdite-shapeshifter-scout.png"
  }
]

=== lvisintini/imperial-assault-data/data/campaign-regular-side-missions.json
[
  {
    "id": "daa07dd7-1b27-5596-9ded-de7c48cd0e0f",
    "name": "Canyon Run",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/canyon-run.png"
  },
  {
    "id": "c67e3bb7-3de1-5e39-9109-544c8052ec8c",
    "name": "A Simple Task",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/a-simple-task.png"
  },
  {
    "id": "552cc30a-a597-59f5-bbf1-f94fbdfa9a39",
    "name": "Generous Donations",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/generous-donations.png"
  },
  {
    "id": "4f5b7161-d467-5e06-9480-de07a1763d6e",
    "name": "Luxury Cruise",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/luxury-cruise.png"
  },
  {
    "id": "75a08b34-3887-55ea-955d-0ac3469cad81",
    "name": "Sympathy for the Rebellion",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/sympathy-for-the-rebellion.png"
  },
  {
    "id": "352e4f51-3f07-53bb-99a7-4da37c834f6b",
    "name": "Viper's Den",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/vipers-den.png"
  },
  {
    "id": "484690b3-cd69-54b0-92fa-fd5537f7a0de",
    "name": "Cloud City's Secret",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/cloud-citys-secret.png"
  },
  {
    "id": "0309f344-9aa0-52ac-a7fa-0340fd70e61d",
    "name": "Freedom Fighters",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/freedom-fighters.png"
  },
  {
    "id": "d7505130-5266-5969-bae6-1636f7c06664",
    "name": "Hostile Takeover",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/hostile-takeover.png"
  },
  {
    "id": "771f18ae-4814-5557-a603-2de10dc4ecc7",
    "name": "Perilous Hunt",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/perilous-hunt.png"
  },
  {
    "id": "ce392f3f-3007-5091-8a03-1fda3eeed6bb",
    "name": "Civil Unrest",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/civil-unrest.png"
  },
  {
    "id": "0522ba28-84e3-5953-9059-9bc0e14605ed",
    "name": "Call to Action",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/call-to-action.png"
  },
  {
    "id": "69e47788-a66e-5e50-9514-de150d3a339d",
    "name": "The Final Order",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/the-final-order.png"
  },
  {
    "id": "03f4e042-9cd9-54a0-b7b1-1ced8189b2f8",
    "name": "Celebration",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/celebration.png"
  },
  {
    "id": "63813379-f900-5a2c-a9c7-974c9d8b0c3c",
    "name": "Imperial Entanglements",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/imperial-entanglements.png"
  },
  {
    "id": "4ec0a911-ee5a-52a8-9ef2-7072d1460848",
    "name": "Into the Unknown",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/into-the-unknown.png"
  },
  {
    "id": "96c41011-61b3-58ed-bbd3-193c0973f6cf",
    "name": "Paying Debts",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-regular-side-missions/paying-debts.png"
  }
]

=== lvisintini/imperial-assault-data/data/condition-cards.json
[
  {
    "id": "4def469d-0db7-5306-92be-eff4307f757d",
    "name": "Bleeding",
    "back_id": "47c5d0a3-0dc7-5a61-b536-31b15ce3ecf0",
    "image": "condition-cards/bleeding.png"
  },
  {
    "id": "bbeb6a4c-4767-52d0-a0ac-01423dd6b20e",
    "name": "Focused",
    "back_id": "6721ed65-fdd8-5304-8659-1e4813502107",
    "image": "condition-cards/focused.png"
  },
  {
    "id": "2d38bd5d-67a0-5b00-962a-c1e9b507fe68",
    "name": "Stunned",
    "back_id": "45e57cfd-e8f7-552d-8a01-e113991992bf",
    "image": "condition-cards/stunned.png"
  },
  {
    "id": "47d9361e-aaa7-58f8-9b2a-3dedb592d663",
    "name": "Weakened",
    "back_id": "f7a6153b-2dea-5405-95b1-e866977d1b08",
    "image": "condition-cards/weakened.png"
  },
  {
    "id": "e64e5a82-3604-5aae-9868-3195ce17391e",
    "name": "Hidden",
    "back_id": "eb2532e7-bca4-562d-9514-927a736412b6",
    "image": "condition-cards/hidden.png"
  }
]

=== lvisintini/imperial-assault-data/data/campaign-ally-side-mission-cards.json
[
  {
    "id": "7fd909d1-3c8f-5acc-8a5f-9792ed50275e",
    "name": "Hunted Down",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/hunted-down.png"
  },
  {
    "id": "8e295903-c4ad-5d19-aacd-a90aa9db67df",
    "name": "Homecoming",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/homecoming.png"
  },
  {
    "id": "1cd8ae76-c421-5b9b-92f2-85b48aed6617",
    "name": "Sorry About the Mess",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/sorry-about-the-mess.png"
  },
  {
    "id": "262278b2-b047-5e59-b6a0-42ee56a1d763",
    "name": "Target of Opportunity",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/target-of-opportunity.png"
  },
  {
    "id": "4fc24915-1735-5557-b55c-2a7b0b1ec341",
    "name": "The Spice Job",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/the-spice-job.png"
  },
  {
    "id": "2801f938-3045-5f38-a928-b098bb473f44",
    "name": "Reclamation",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/reclamation.png"
  },
  {
    "id": "1fa08add-1271-5f3f-9e18-0f21a1be597f",
    "name": "Race on Ryloth",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/race-on-ryloth.png"
  },
  {
    "id": "b37c4013-dfc8-51ed-bc81-eb45f25885f2",
    "name": "Siege on Geonosis",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/siege-on-geonosis.png"
  },
  {
    "id": "9de83d9d-0fc9-54fd-8f26-fc9bea16f657",
    "name": "Executive Overreach",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/executive-overreach.png"
  },
  {
    "id": "361818b7-d8a5-5359-8fc1-d07f36a06f2c",
    "name": "Intimidation Factor",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/intimidation-factor.png"
  },
  {
    "id": "77e3b415-91c1-5739-8915-13c7d35e63f1",
    "name": "Armed and Operational",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/armed-and-operational.png"
  },
  {
    "id": "cd39e514-f8bd-50b4-a5f9-2ec62e2f2f36",
    "name": "Brace for Impact",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/brace-for-impact.png"
  },
  {
    "id": "38a87199-4afd-5aed-af9c-0b44a6c65350",
    "name": "Open to Interpretation",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/open-to-interpretation.png"
  },
  {
    "id": "12088b51-5e2c-5a79-a684-ee767207d285",
    "name": "Brute Force",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/brute-force.png"
  },
  {
    "id": "6fbd1306-5424-5188-b927-d32171a3968c",
    "name": "Precious Cargo",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/precious-cargo.png"
  },
  {
    "id": "0cad7dd5-1794-5590-a924-7ef7849bac4c",
    "name": "Snowcrash",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/snowcrash.png"
  },
  {
    "id": "a4c3e6aa-cc5b-5fd8-a9c9-a349b7e00aff",
    "name": "Communication Breakdown",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/communication-breakdown.png"
  },
  {
    "id": "4eba8c92-149c-5a6c-9ff9-d4c050ae8a2a",
    "name": "Deadly Transmission",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/deadly-transmission.png"
  },
  {
    "id": "a19a16b9-7049-5e75-8faa-00a22d82916d",
    "name": "Strike Force Xesh",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/strike-force-xesh.png"
  },
  {
    "id": "299cc509-e046-5fc6-9aa8-42b0c5333ab7",
    "name": "A Light in the Darkness",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/a-light-in-the-darkness.png"
  },
  {
    "id": "4d2082b6-6325-5d67-b7ca-0f4326344b3e",
    "name": "Phantom Extraction",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/phantom-extraction.png"
  },
  {
    "id": "d8c05b3b-0dc4-5e6e-aad3-c733da068c6a",
    "name": "Home Invasion",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-mission-cards/home-invasion.png"
  }
]

=== lvisintini/imperial-assault-data/data/campaign-ally-side-missions.json
[
  {
    "id": "7fd909d1-3c8f-5acc-8a5f-9792ed50275e",
    "name": "Hunted Down",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/hunted-down.png"
  },
  {
    "id": "8e295903-c4ad-5d19-aacd-a90aa9db67df",
    "name": "Homecoming",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/homecoming.png"
  },
  {
    "id": "1cd8ae76-c421-5b9b-92f2-85b48aed6617",
    "name": "Sorry About the Mess",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/sorry-about-the-mess.png"
  },
  {
    "id": "262278b2-b047-5e59-b6a0-42ee56a1d763",
    "name": "Target of Opportunity",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/target-of-opportunity.png"
  },
  {
    "id": "4fc24915-1735-5557-b55c-2a7b0b1ec341",
    "name": "The Spice Job",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/the-spice-job.png"
  },
  {
    "id": "2801f938-3045-5f38-a928-b098bb473f44",
    "name": "Reclamation",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/reclamation.png"
  },
  {
    "id": "1fa08add-1271-5f3f-9e18-0f21a1be597f",
    "name": "Race on Ryloth",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/race-on-ryloth.png"
  },
  {
    "id": "b37c4013-dfc8-51ed-bc81-eb45f25885f2",
    "name": "Siege on Geonosis",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/siege-on-geonosis.png"
  },
  {
    "id": "9de83d9d-0fc9-54fd-8f26-fc9bea16f657",
    "name": "Executive Overreach",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/executive-overreach.png"
  },
  {
    "id": "361818b7-d8a5-5359-8fc1-d07f36a06f2c",
    "name": "Intimidation Factor",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/intimidation-factor.png"
  },
  {
    "id": "77e3b415-91c1-5739-8915-13c7d35e63f1",
    "name": "Armed and Operational",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/armed-and-operational.png"
  },
  {
    "id": "cd39e514-f8bd-50b4-a5f9-2ec62e2f2f36",
    "name": "Brace for Impact",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/brace-for-impact.png"
  },
  {
    "id": "38a87199-4afd-5aed-af9c-0b44a6c65350",
    "name": "Open to Interpretation",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/open-to-interpretation.png"
  },
  {
    "id": "12088b51-5e2c-5a79-a684-ee767207d285",
    "name": "Brute Force",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/brute-force.png"
  },
  {
    "id": "6fbd1306-5424-5188-b927-d32171a3968c",
    "name": "Precious Cargo",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/precious-cargo.png"
  },
  {
    "id": "0cad7dd5-1794-5590-a924-7ef7849bac4c",
    "name": "Snowcrash",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/snowcrash.png"
  },
  {
    "id": "a4c3e6aa-cc5b-5fd8-a9c9-a349b7e00aff",
    "name": "Communication Breakdown",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/communication-breakdown.png"
  },
  {
    "id": "4eba8c92-149c-5a6c-9ff9-d4c050ae8a2a",
    "name": "Deadly Transmission",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/deadly-transmission.png"
  },
  {
    "id": "a19a16b9-7049-5e75-8faa-00a22d82916d",
    "name": "Strike Force Xesh",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/strike-force-xesh.png"
  },
  {
    "id": "299cc509-e046-5fc6-9aa8-42b0c5333ab7",
    "name": "A Light in the Darkness",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/a-light-in-the-darkness.png"
  },
  {
    "id": "4d2082b6-6325-5d67-b7ca-0f4326344b3e",
    "name": "Phantom Extraction",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/phantom-extraction.png"
  },
  {
    "id": "d8c05b3b-0dc4-5e6e-aad3-c733da068c6a",
    "name": "Home Invasion",
    "back_id": "dcf85a36-1935-5309-8051-5b1ba6516835",
    "image": "campaign-ally-side-missions/home-invasion.png"
  }
]

=== lvisintini/imperial-assault-data/data/campaign-threat-missions.json
[
  {
    "id": "4fd9b597-812c-5ca3-9cf1-7da10dde873a",
    "name": "Escape from Cloud City",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-missions/escape-from-cloud-city.png"
  },
  {
    "id": "c6faf287-3f47-58ba-878a-e2778a9d8222",
    "name": "Scouring of the Homestead",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-missions/scouring-of-the-homestead.png"
  },
  {
    "id": "9ed8be42-c8be-5214-87b1-68388e52a592",
    "name": "Survival of the Fittest",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-missions/survival-of-the-fittest.png"
  },
  {
    "id": "54dad23c-4409-51c2-bfac-e12dd38457e8",
    "name": "The Hard Way",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-missions/the-hard-way.png"
  }
]

=== lvisintini/imperial-assault-data/data/campaign-story-missions.json
[
  {
    "id": "fc7f612f-31f6-5553-b2f8-6d4a10cdec0b",
    "name": "Disaster",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/disaster.png"
  },
  {
    "id": "ca140189-7961-54d4-b1b7-bfc8e851ce79",
    "name": "Home Front",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/home-front.png"
  },
  {
    "id": "c0e9884f-5105-5af2-ae15-9d0e87ac015f",
    "name": "One Step Behind",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/one-step-behind.png"
  },
  {
    "id": "505d1d01-157a-573d-8796-bc6dcf69f5a8",
    "name": "Our Last Hope",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/our-last-hope.png"
  },
  {
    "id": "4f4d1c31-2333-5e70-a4c7-15ba0f6085f6",
    "name": "Rescue Ops",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/rescue-ops.png"
  },
  {
    "id": "764c7038-a0d7-559d-aa04-7f32a842e518",
    "name": "Return to Echo Base",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/return-to-echo-base.png"
  },
  {
    "id": "ff7455ac-5990-5fbb-a621-77e1dcc61125",
    "name": "The Last Line",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/the-last-line.png"
  },
  {
    "id": "f179602c-4a26-58c7-9d56-a00b321be3c2",
    "name": "White Noise",
    "back_id": "66ef8c5b-29c8-5e05-b1e6-fe1cdb165198",
    "image": "campaign-story-missions/white-noise.png"
  },
  {
    "id": "ac081d23-53c9-541d-92dc-48a04bd84be9",
    "name": "A New Threat",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/a-new-threat.png"
  },
  {
    "id": "406d6db5-4188-5774-8079-8932fafef5dc",
    "name": "Chain of Command",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/chain-of-command.png"
  },
  {
    "id": "0302d097-5954-5e79-831a-b966c579ea91",
    "name": "Desperate Hour",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/despertate-hour.png"
  },
  {
    "id": "d8823fa9-28d5-587e-b082-6eef63381900",
    "name": "Drawn In",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/drawn-in.png"
  },
  {
    "id": "3e5f52c8-a651-5061-a088-7d6e8c8c85df",
    "name": "Fly Solo",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/fly-solo.png"
  },
  {
    "id": "cfc8ef72-404c-5c21-a6a5-1651d6f41961",
    "name": "Imperial Hospitality",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/imperial-hospitality.png"
  },
  {
    "id": "02dcedea-7ff1-5542-ac44-a051bbf310a8",
    "name": "Incoming",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/incoming.png"
  },
  {
    "id": "b2db846a-7d76-5816-aea1-368d5e9d519b",
    "name": "Last Stand",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/last-stand.png"
  },
  {
    "id": "bd6b0551-f71e-593d-9095-f9cfb3000941",
    "name": "The Source",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/the-source.png"
  },
  {
    "id": "5026f5e9-c8ff-5de8-afe1-02d6a73db2a9",
    "name": "Under Siege",
    "back_id": "21f220a4-b7a2-5095-b44b-f18828461dfc",
    "image": "campaign-story-missions/under-siege.png"
  },
  {
    "id": "93cb831c-d6e7-59ba-a8b0-d0b7b7f2b6e2",
    "name": "Almost Home",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/almost-home.png"
  },
  {
    "id": "2f96b6ec-6b0b-50a1-baab-0a62c041d952",
    "name": "Dangerous Allies",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/dangerous-allies.png"
  },
  {
    "id": "db1860c8-7832-5497-ab46-666ce9372762",
    "name": "Execute the Plan",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/execute-the-plan.png"
  },
  {
    "id": "60a9a403-4373-5c2d-a3f5-3ba170299aca",
    "name": "From All Sides",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/from-all-sides.png"
  },
  {
    "id": "be1144ec-9be7-5386-899f-ddac397b8f3d",
    "name": "Hostile Negotiations",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/hostile-negotiations.png"
  },
  {
    "id": "8fbb3179-ce3c-57df-8179-afd76d8cb601",
    "name": "Moment of Fate",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/moment-of-fate.png"
  },
  {
    "id": "eaef766b-6a3e-50d6-9d7c-0e3149f37d78",
    "name": "Mutiny",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/mutiny.png"
  },
  {
    "id": "7a297013-1c25-5127-808c-a925b0e59088",
    "name": "Overcharged",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/overcharged.png"
  },
  {
    "id": "bb25a423-f800-5232-a3e1-1b551e599aaf",
    "name": "Storming the Palace",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/storming-the-palace.png"
  },
  {
    "id": "e2c497ae-e255-5308-af15-1df8beebf811",
    "name": "Trophy Hunting",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/trophy-hunting.png"
  },
  {
    "id": "e0e0b002-7b79-5bac-8fa4-457d5a6fc334",
    "name": "Turf War",
    "back_id": "f4424734-8b5f-548e-892c-0e9b9cb149c4",
    "image": "campaign-story-missions/turf-war.png"
  },
  {
    "id": "dcc07cea-ecdd-5e48-8e87-4230f0cf4d7f",
    "name": "Capital Escape",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/capital-escape.png"
  },
  {
    "id": "916120f0-9c39-57b7-9e95-d21be781d9ff",
    "name": "Disruption",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/disruption.png"
  },
  {
    "id": "ed74833a-e4da-5d59-9098-934b0bcb7c53",
    "name": "Double Agent",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/double-agent.png"
  },
  {
    "id": "48bbb394-89cf-5c61-8613-01b99d194dbf",
    "name": "Enemies Closer",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/enemies-closer.png"
  },
  {
    "id": "673873cf-1919-549b-807b-af0800597c9c",
    "name": "From Dark Clutches",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/from-dark-clutches.png"
  },
  {
    "id": "c43b6962-fd67-5890-aedd-c0f92bd51247",
    "name": "History Repeats",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/history-repeats.png"
  },
  {
    "id": "d02db3c4-cc01-55ff-927e-b8be338eb9b9",
    "name": "Inside Man",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/inside-man.png"
  },
  {
    "id": "219304ae-96a1-5676-8a77-8a34bf3a55a7",
    "name": "Into a Corner",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/into-a-corner.png"
  },
  {
    "id": "50a9b1f7-6a99-5f1f-849e-7d726fd524b0",
    "name": "On the Run",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/on-the-run.png"
  },
  {
    "id": "d9a7025a-85af-55f4-a8f7-c400a02689a1",
    "name": "On the Trail",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/on-the-trail.png"
  },
  {
    "id": "4aa85336-e8fd-5355-928c-ee74ff7e3b9e",
    "name": "The Realm of the Dark Side",
    "back_id": "dc9f7288-fb83-521d-802c-edcfda9f5661",
    "image": "campaign-story-missions/the-realm-of-the-dark-side.png"
  },
  {
    "id": "cfc47b02-f625-45de-9e3b-c799b3ceaf3c",
    "name": "Aftermath",
    "back_id": null,
    "image": null
  },
  {
    "id": "59da4503-74fe-4dd4-a579-078b34e75d65",
    "name": "Captured",
    "back_id": null,
    "image": null
  },
  {
    "id": "0f7f18fa-c1c9-49ce-8a4b-9b0e8fe55099",
    "name": "Dark Recon",
    "back_id": null,
    "image": null
  },
  {
    "id": "c864b31a-823f-44c2-89e2-4e5c0a43ba38",
    "name": "The Battle of Hoth",
    "back_id": null,
    "image": null
  },
  {
    "id": "78e60f82-756d-46b5-a15c-dacb4741dbc2",
    "name": "Trespass",
    "back_id": null,
    "image": null
  }
]

=== lvisintini/imperial-assault-data/data/campaign-threat-mission-cards.json
[
  {
    "id": "4fd9b597-812c-5ca3-9cf1-7da10dde873a",
    "name": "Escape from Cloud City",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-mission-cards/escape-from-cloud-city.png"
  },
  {
    "id": "c6faf287-3f47-58ba-878a-e2778a9d8222",
    "name": "Scouring of the Homestead",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-mission-cards/scouring-of-the-homestead.png"
  },
  {
    "id": "9ed8be42-c8be-5214-87b1-68388e52a592",
    "name": "Survival of the Fittest",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-mission-cards/survival-of-the-fittest.png"
  },
  {
    "id": "54dad23c-4409-51c2-bfac-e12dd38457e8",
    "name": "The Hard Way",
    "back_id": "980170a9-a10d-5d59-860c-a3dc6d33a273",
    "image": "campaign-threat-mission-cards/the-hard-way.png"
  }
]
