=== lvisintini/imperial-assault-data/schemas/command-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "command-cards.json#",
  "title": "Schema for the command cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Command card name",
      "minLength": 1
    },
    "iaspec": {
      "type": "string",
      "description": "iaspec code",
      "minLength": 1
    },
    "cost": {
      "description": "The cost associated with using this command card.",
      "type": "integer",
      "minimum": 0
    },
    "limit": {
      "description": "Determines the maximum number of copies of this command card in your command deck.",
      "type": "integer",
      "minimum": 1,
      "maximum": 3
    },
    "image": {
      "description": "The file path for this command card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    }
  },
  "required": [
    "id",
    "iaspec",
    "name",
    "cost",
    "limit",
    "image"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/command-cards.json
[
  {
    "id": 0,
    "name": "A Powerful Influence",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/a-powerful-influence.png",
    "iaspec": "apowerfulinfluence"
  },
  {
    "id": 1,
    "name": "Adrenaline",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/adrenaline.png",
    "iaspec": "adrenaline"
  },
  {
    "id": 2,
    "name": "Advance Warning",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/advance-warning.png",
    "iaspec": "advancewarning"
  },
  {
    "id": 3,
    "name": "Against the Odds",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/against-the-odds.png",
    "iaspec": "againsttheodds"
  },
  {
    "id": 4,
    "name": "Assassinate",
    "cost": 3,
    "limit": 1,
    "image": "command-cards/assassinate.png",
    "iaspec": "assassinate"
  },
  {
    "id": 5,
    "name": "Ballistics Matrix",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/ballistics-matrix.png",
    "iaspec": "ballisticsmatrix"
  },
  {
    "id": 6,
    "name": "Battlefield Awareness",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/battlefield-awareness.png",
    "iaspec": "battlefieldawareness"
  },
  {
    "id": 7,
    "name": "Behind Enemy Lines",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/behind-enemy-lines.png",
    "iaspec": "behindenemylines"
  },
  {
    "id": 8,
    "name": "Black Market Prices",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/black-market-prices.png",
    "iaspec": "blackmarketprices"
  },
  {
    "id": 9,
    "name": "Bladestorm",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/bladestorm.png",
    "iaspec": "bladestorm"
  },
  {
    "id": 10,
    "name": "Blaze of Glory",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/blaze-of-glory.png",
    "iaspec": "blazeofglory"
  },
  {
    "id": 11,
    "name": "Blitz",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/blitz.png",
    "iaspec": "blitz"
  },
  {
    "id": 12,
    "name": "Blood Feud",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/blood-feud.png",
    "iaspec": "bloodfeud"
  },
  {
    "id": 13,
    "name": "Bodyguard",
    "cost": 1,
    "limit": 2,
    "image": "command-cards/bodyguard.png",
    "iaspec": "bodyguard"
  },
  {
    "id": 14,
    "name": "Brace Yourself",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/brace-yourself.png",
    "iaspec": "braceyourself"
  },
  {
    "id": 15,
    "name": "Brace for Impact",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/brace-for-impact.png",
    "iaspec": "braceforimpact"
  },
  {
    "id": 16,
    "name": "Burst Fire",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/burst-fire.png",
    "iaspec": "burstfire"
  },
  {
    "id": 17,
    "name": "Call the Vanguard",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/call-the-vanguard.png",
    "iaspec": "callthevanguard"
  },
  {
    "id": 18,
    "name": "Camouflage",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/camouflage.png",
    "iaspec": "camouflage"
  },
  {
    "id": 19,
    "name": "Capture The Weary",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/capture-the-weary.png",
    "iaspec": "capturetheweary"
  },
  {
    "id": 20,
    "name": "Cavalry Charge",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/cavalry-charge.png",
    "iaspec": "cavalrycharge"
  },
  {
    "id": 21,
    "name": "Celebration",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/celebration.png",
    "iaspec": "celebration"
  },
  {
    "id": 22,
    "name": "Change of Plans",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/change-of-plans.png",
    "iaspec": "changeofplans"
  },
  {
    "id": 23,
    "name": "Cheat to Win",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/cheat-to-win.png",
    "iaspec": "cheattowin"
  },
  {
    "id": 24,
    "name": "Close the Gap",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/close-the-gap.png",
    "iaspec": "closethegap"
  },
  {
    "id": 25,
    "name": "Collect Intel",
    "cost": 1,
    "limit": 2,
    "image": "command-cards/collect-intel.png",
    "iaspec": "collectintel"
  },
  {
    "id": 26,
    "name": "Comm Disruption",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/comm-disruption.png",
    "iaspec": "commdisruption"
  },
  {
    "id": 27,
    "name": "Coordinated Attack",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/coordinated-attack.png",
    "iaspec": "coordinatedattack"
  },
  {
    "id": 28,
    "name": "Counter Attack",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/counter-attack.png",
    "iaspec": "counterattack"
  },
  {
    "id": 29,
    "name": "Covering Fire",
    "cost": 3,
    "limit": 1,
    "image": "command-cards/covering-fire.png",
    "iaspec": "coveringfire"
  },
  {
    "id": 30,
    "name": "Cripple",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/cripple.png",
    "iaspec": "cripple"
  },
  {
    "id": 31,
    "name": "Cruel Strike",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/cruel-strike.png",
    "iaspec": "cruelstrike"
  },
  {
    "id": 32,
    "name": "Crush",
    "cost": 3,
    "limit": 1,
    "image": "command-cards/crush.png",
    "iaspec": "crush"
  },
  {
    "id": 33,
    "name": "Cut Lines",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/cut-lines.png",
    "iaspec": "cutlines"
  },
  {
    "id": 34,
    "name": "Dangerous Bargains",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/dangerous-bargains.png",
    "iaspec": "dangerousbargains"
  },
  {
    "id": 35,
    "name": "Data Theft",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/data-theft.png",
    "iaspec": "datatheft"
  },
  {
    "id": 36,
    "name": "Deadeye",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/deadeye.png",
    "iaspec": "deadeye"
  },
  {
    "id": 37,
    "name": "Deadly Precision",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/deadly-precision.png",
    "iaspec": "deadlyprecision"
  },
  {
    "id": 38,
    "name": "Debts Repaid",
    "cost": 3,
    "limit": 1,
    "image": "command-cards/debts-repaid.png",
    "iaspec": "debtsrepaid"
  },
  {
    "id": 39,
    "name": "Deflection",
    "cost": 1,
    "limit": 2,
    "image": "command-cards/deflection.png",
    "iaspec": "deflection"
  },
  {
    "id": 40,
    "name": "Devotion",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/devotion.png",
    "iaspec": "devotion"
  },
  {
    "id": 41,
    "name": "Dirty Trick",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/dirty-trick.png",
    "iaspec": "dirtytrick"
  },
  {
    "id": 42,
    "name": "Disable",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/disable.png",
    "iaspec": "disable"
  },
  {
    "id": 43,
    "name": "Disorient",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/disorient.png",
    "iaspec": "disorient"
  },
  {
    "id": 44,
    "name": "Draw",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/draw.png",
    "iaspec": "draw"
  },
  {
    "id": 45,
    "name": "Eerie Visage",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/eerie-visage.png",
    "iaspec": "eerievisage"
  },
  {
    "id": 46,
    "name": "Efficient Travel",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/efficient-travel.png",
    "iaspec": "efficienttravel"
  },
  {
    "id": 47,
    "name": "Element of Surprise",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/element-of-surprise.png",
    "iaspec": "elementofsurprise"
  },
  {
    "id": 48,
    "name": "Emergency Aid",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/emergency-aid.png",
    "iaspec": "emergencyaid"
  },
  {
    "id": 49,
    "name": "Endless Reserves",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/endless-reserves.png",
    "iaspec": "endlessreserves"
  },
  {
    "id": 50,
    "name": "Espionage Mastery",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/espionage-mastery.png",
    "iaspec": "espionagemastery"
  },
  {
    "id": 51,
    "name": "Etiquette and Protocol",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/etiquette-and-protocol.png",
    "iaspec": "etiquetteandprotocol"
  },
  {
    "id": 52,
    "name": "Evacuate",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/evacuate.png",
    "iaspec": "evacuate"
  },
  {
    "id": 53,
    "name": "Explosive Weaponry",
    "cost": 1,
    "limit": 2,
    "image": "command-cards/explosive-weaponry.png",
    "iaspec": "explosiveweaponry"
  },
  {
    "id": 54,
    "name": "Expose Weakness",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/expose-weakness.png",
    "iaspec": "exposeweakness"
  },
  {
    "id": 55,
    "name": "Extra Protection",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/extra-protection.png",
    "iaspec": "extraprotection"
  },
  {
    "id": 56,
    "name": "Fatal Deception",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/fatal-deception.png",
    "iaspec": "fataldeception"
  },
  {
    "id": 57,
    "name": "Feral Swipes",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/feral-swipes.png",
    "iaspec": "feralswipes"
  },
  {
    "id": 58,
    "name": "Ferocity",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/ferocity.png",
    "iaspec": "ferocity"
  },
  {
    "id": 59,
    "name": "Field Tactician",
    "cost": 1,
    "limit": 1,
    "image": "command-cards/field-tactician.png",
    "iaspec": "fieldtactician"
  },
  {
    "id": 60,
    "name": "Fleet Footed",
    "cost": 0,
    "limit": 1,
    "image": "command-cards/fleet-footed.png",
    "iaspec": "fleetfooted"
  },
  {
    "id": 61,
    "name": "Flurry of Blades",
    "cost": 2,
    "limit": 1,
    "image": "command-cards/flurry-of-blades.png",
    "iaspec": "flurryofblades"
  },
  {
    "id": 62,
    "name": "Focus",
    "cost": 1,
