=== lvisintini/imperial-assault-data/schemas/companion-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "companion-cards.json#",
  "title": "Schema for the companion cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "description": "Id for entry: a UUID (see docs/data-model.md).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "name": {
      "type": "string",
      "description": "Companion card name",
      "minLength": 1
    },
    "iaspec": {
      "type": "string",
      "description": "iaspec code",
      "minLength": 1
    },
    "back_id": {
      "description": "Foreign key to this card's back in data/card-backs.json.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "image": {
      "description": "The file path for this companion card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "traits": {
      "type": "array",
      "minItems": 1,
      "description": "Traits that apply to this companion card.",
      "uniqueItems": true,
      "items": {
        "description": "A trait that applies to this companion.",
        "$ref": "definitions.json#/definitions/deployment-trait"
      }
    },
    "health": {
      "type": "integer",
      "description": "This companion's health",
      "minimum": 1
    },
    "speed": {
      "type": "integer",
      "description": "This companion's speed",
      "minimum": 1
    }
  },
  "required": [
    "id",
    "iaspec",
    "name",
    "back_id",
    "image",
    "traits",
    "health",
    "speed"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/companion-cards.json
[
  {
    "id": "5d883b8b-ea0e-581d-98c4-c4ccadd7558f",
    "name": "Cam Droid",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/cam-droid.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "camdroid",
    "health": 3,
    "speed": 5
  },
  {
    "id": "3292445b-6a2e-5e7c-be18-ceee868d17bf",
    "name": "Junk Droid",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/junk-droid.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "junkdroid",
    "health": 1,
    "speed": 4
  },
  {
    "id": "8b8ee864-1614-5f13-961e-f0c5188c4e10",
    "name": "R5 Astromech",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/r5-astromech.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "r5astromech",
    "health": 4,
    "speed": 3
  },
  {
    "id": "da4e58ff-ee29-5b77-8396-7f0e66adfe41",
    "name": "Pit Droid",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/pit-droid.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "pitdroid",
    "health": 3,
    "speed": 4
  },
  {
    "id": "4a8d861a-cf73-57da-b713-ff6ab1e350d3",
    "name": "Salacious B. Crumb",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/salacious-b-crumb.png",
    "traits": [
      "Brawler"
    ],
    "iaspec": "salaciousbcrumb",
    "health": 6,
    "speed": 3
  },
  {
    "id": "02506600-fc27-51bc-9b1e-9c6217aa18cb",
    "name": "88-Z",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/88-z.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "88z",
    "health": 4,
    "speed": 3
  },
  {
    "id": "76900d88-dd01-5354-a3da-92907c671a73",
    "name": "J4X-7",
    "back_id": "092b531f-0b3a-5a06-8d68-80217ea29f5d",
    "image": "companion-cards/j4x-7.png",
    "traits": [
      "Droid"
    ],
    "iaspec": "j4x7",
    "health": 4,
    "speed": 3
  }
]
