=== lvisintini/imperial-assault-data/schemas/epilogue-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "epilogue-cards.json#",
  "title": "Schema for the epilogue cards data file: how a mission ends, one card per outcome",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "description": "Id for entry: a UUID (see docs/data-model.md).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "name": {
      "type": "string",
      "description": "Epilogue name (without the \"Epilogue:\" prefix)",
      "minLength": 1
    },
    "mission_id": {
      "description": "Foreign key to the mission in data/missions.json (the index) the epilogue ends.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "back_id": {
      "description": "Foreign key to this card's back in data/card-backs.json.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "image": {
      "description": "The file path for this epilogue card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    }
  },
  "required": [
    "id",
    "name",
    "mission_id",
    "back_id",
    "image"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/epilogue-cards.json
[
  {
    "id": "bbae304c-64bb-4c07-9c2d-581a14cf0a07",
    "name": "Sparks",
    "mission_id": "98f6ad21-f683-4e2b-a8a9-d32aaca71440",
    "back_id": "455fa36e-a2f9-420d-a7f0-d2a2540a23c6",
    "image": "epilogue-cards/sparks.png"
  },
  {
    "id": "01c7efa7-87ee-47d2-a7f8-808e0a96218f",
    "name": "Comeuppance",
    "mission_id": "98f6ad21-f683-4e2b-a8a9-d32aaca71440",
    "back_id": "455fa36e-a2f9-420d-a7f0-d2a2540a23c6",
    "image": "epilogue-cards/comeuppance.png"
  },
  {
    "id": "bd43628c-7a8c-480b-b3f2-ccb230205ad7",
    "name": "Loose Ends",
    "mission_id": "f0a58df5-b7e1-4668-94e6-54dda489dee8",
    "back_id": "5a94e36f-52bc-471f-a161-bc298127cb38",
    "image": "epilogue-cards/loose-ends.png"
  },
  {
    "id": "d8d95e7a-5812-4f2f-8d7f-094e299ab704",
    "name": "Score Settled",
    "mission_id": "f0a58df5-b7e1-4668-94e6-54dda489dee8",
    "back_id": "5a94e36f-52bc-471f-a161-bc298127cb38",
    "image": "epilogue-cards/score-settled.png"
  },
  {
    "id": "53a2c58d-d77e-4134-bca6-66c19426b42a",
    "name": "Blinded",
    "mission_id": "389deb25-eded-4082-b353-d711d4d61f0b",
    "back_id": "dd9c9ff9-04d3-4413-a8a1-d5f82d1c6e81",
    "image": "epilogue-cards/blinded.png"
  },
  {
    "id": "9d874562-8140-4caa-b48c-057510db2903",
    "name": "Scramble",
    "mission_id": "389deb25-eded-4082-b353-d711d4d61f0b",
    "back_id": "dd9c9ff9-04d3-4413-a8a1-d5f82d1c6e81",
    "image": "epilogue-cards/scramble.png"
  },
  {
    "id": "7c7dbdcb-ac7c-42d8-b1c4-bdcdd9859241",
    "name": "Lay Low",
    "mission_id": "009a3795-b9a6-4a6c-8a9e-da1ddc3176bb",
    "back_id": "b5717817-51f5-4f58-b481-b5a8a097c4e6",
    "image": "epilogue-cards/lay-low.png"
  },
  {
    "id": "2e0688ed-f52b-4380-847a-6886058e1fbf",
    "name": "Liberators",
    "mission_id": "009a3795-b9a6-4a6c-8a9e-da1ddc3176bb",
    "back_id": "b5717817-51f5-4f58-b481-b5a8a097c4e6",
    "image": "epilogue-cards/liberators.png"
  }
]
