=== lvisintini/imperial-assault-data/schemas/map-tiles.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "map-tiles.json#",
  "title": "Schema for the map tiles data file: the double-sided tiles maps are built from",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "description": "Id for entry: a UUID (see docs/data-model.md).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "name": {
      "type": "string",
      "description": "The tile's product and number: \"Core Set 01\", \"Twin Shadows 01\".",
      "minLength": 1
    },
    "number": {
      "type": "integer",
      "description": "The number printed on the tile.",
      "minimum": 1
    },
    "side_a": {
      "description": "The file path for the tile's A side, cut on its outline (transparent notches).",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "side_b": {
      "description": "The file path for the tile's B side, cut on its outline (transparent notches).",
      "$ref": "definitions.json#/definitions/image-file-path"
    }
  },
  "required": [
    "id",
    "name",
    "number",
    "side_a",
    "side_b"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/map-tiles.json
[
  {
    "id": "ed923def-b487-426b-8d93-f22f9ac6e2e3",
    "name": "Core Set 01",
    "number": 1,
    "side_a": "map-tiles/core-set-01-a.png",
    "side_b": "map-tiles/core-set-01-b.png"
  },
  {
    "id": "a52c1618-7b6a-40a6-b665-ead02b9ac018",
    "name": "Core Set 02",
    "number": 2,
    "side_a": "map-tiles/core-set-02-a.png",
    "side_b": "map-tiles/core-set-02-b.png"
  },
  {
    "id": "a944ef4c-c04d-4a59-96cb-e79aef1cb344",
    "name": "Core Set 03",
    "number": 3,
    "side_a": "map-tiles/core-set-03-a.png",
    "side_b": "map-tiles/core-set-03-b.png"
  },
  {
    "id": "323ea6f1-51d8-4c1e-86c1-3f1d28eae71e",
    "name": "Core Set 04",
    "number": 4,
    "side_a": "map-tiles/core-set-04-a.png",
    "side_b": "map-tiles/core-set-04-b.png"
  },
  {
    "id": "139c7b3f-6928-4558-8e31-6dce7d1fc0ed",
    "name": "Core Set 05",
    "number": 5,
    "side_a": "map-tiles/core-set-05-a.png",
    "side_b": "map-tiles/core-set-05-b.png"
  },
  {
    "id": "6ba79f94-909a-458f-ac62-88d46829b428",
    "name": "Core Set 06",
    "number": 6,
    "side_a": "map-tiles/core-set-06-a.png",
    "side_b": "map-tiles/core-set-06-b.png"
  },
  {
    "id": "098c49e7-25ec-4ddc-ab6b-d2b39498a365",
    "name": "Core Set 07",
    "number": 7,
    "side_a": "map-tiles/core-set-07-a.png",
    "side_b": "map-tiles/core-set-07-b.png"
  },
  {
    "id": "99502083-5daa-4e4e-acc6-aba1072106f2",
    "name": "Core Set 08",
    "number": 8,
    "side_a": "map-tiles/core-set-08-a.png",
    "side_b": "map-tiles/core-set-08-b.png"
  },
  {
    "id": "7f5e7144-c0d6-488b-bf7a-58c574da0eae",
    "name": "Core Set 09",
    "number": 9,
    "side_a": "map-tiles/core-set-09-a.png",
    "side_b": "map-tiles/core-set-09-b.png"
  },
  {
    "id": "13234ec3-e7f3-49e3-ac54-63662c813b3f",
    "name": "Core Set 10",
    "number": 10,
    "side_a": "map-tiles/core-set-10-a.png",
    "side_b": "map-tiles/core-set-10-b.png"
  },
  {
    "id": "b696f297-33cc-402f-a9d9-810a64f9e263",
    "name": "Core Set 11",
    "number": 11,
    "side_a": "map-tiles/core-set-11-a.png",
    "side_b": "map-tiles/core-set-11-b.png"
  },
  {
    "id": "4f7f3652-0a52-4667-9ca2-ffd9f1040001",
    "name": "Core Set 12",
    "number": 12,
    "side_a": "map-tiles/core-set-12-a.png",
    "side_b": "map-tiles/core-set-12-b.png"
  },
  {
    "id": "3861c46e-5922-49d4-a61f-06710871df30",
    "name": "Core Set 13",
    "number": 13,
    "side_a": "map-tiles/core-set-13-a.png",
    "side_b": "map-tiles/core-set-13-b.png"
  },
  {
    "id": "68e8b019-7436-478c-be4e-607fb11527cd",
    "name": "Core Set 14",
    "number": 14,
    "side_a": "map-tiles/core-set-14-a.png",
    "side_b": "map-tiles/core-set-14-b.png"
  },
  {
    "id": "8278f62b-b448-4987-ab4e-b2379e8cf86b",
    "name": "Core Set 15",
    "number": 15,
    "side_a": "map-tiles/core-set-15-a.png",
    "side_b": "map-tiles/core-set-15-b.png"
  },
  {
    "id": "4af356e5-9be6-4879-8954-1ba4580e87c7",
    "name": "Core Set 16",
    "number": 16,
    "side_a": "map-tiles/core-set-16-a.png",
    "side_b": "map-tiles/core-set-16-b.png"
  },
  {
    "id": "76d4c482-b323-4ab9-9ce4-224607a28d1f",
    "name": "Core Set 17",
    "number": 17,
    "side_a": "map-tiles/core-set-17-a.png",
    "side_b": "map-tiles/core-set-17-b.png"
  },
  {
    "id": "58152319-7388-47ee-aa0b-1ab261a5ea6c",
    "name": "Core Set 18",
    "number": 18,
    "side_a": "map-tiles/core-set-18-a.png",
    "side_b": "map-tiles/core-set-18-b.png"
  },
  {
    "id": "887c355a-b97d-46b1-8714-b30c454b979a",
    "name": "Core Set 19",
    "number": 19,
    "side_a": "map-tiles/core-set-19-a.png",
    "side_b": "map-tiles/core-set-19-b.png"
  },
  {
    "id": "8d309b55-d62e-4d95-9c1e-7da345005e89",
    "name": "Core Set 20",
    "number": 20,
    "side_a": "map-tiles/core-set-20-a.png",
    "side_b": "map-tiles/core-set-20-b.png"
  },
  {
    "id": "bab5cbef-785b-45c2-b54f-8031eaed99d4",
    "name": "Core Set 21",
    "number": 21,
    "side_a": "map-tiles/core-set-21-a.png",
    "side_b": "map-tiles/core-set-21-b.png"
  },
  {
    "id": "65a15c4e-378e-41e6-805a-5c2738254cf3",
    "name": "Core Set 22",
    "number": 22,
    "side_a": "map-tiles/core-set-22-a.png",
    "side_b": "map-tiles/core-set-22-b.png"
  },
  {
    "id": "82e8b296-c11e-4f34-ac98-28378b586a83",
    "name": "Core Set 23",
    "number": 23,
    "side_a": "map-tiles/core-set-23-a.png",
    "side_b": "map-tiles/core-set-23-b.png"
  },
  {
    "id": "eb800ec4-99ee-4f1a-8388-ceea9ed6c70c",
    "name": "Core Set 24",
    "number": 24,
    "side_a": "map-tiles/core-set-24-a.png",
    "side_b": "map-tiles/core-set-24-b.png"
  },
  {
    "id": "5abac59d-9d1c-46d3-a9ba-6d29df68ec6b",
    "name": "Core Set 25",
    "number": 25,
    "side_a": "map-tiles/core-set-25-a.png",
    "side_b": "map-tiles/core-set-25-b.png"
  },
  {
    "id": "f639ee25-6476-4ee8-af07-2fe9543282bc",
    "name": "Core Set 26",
    "number": 26,
    "side_a": "map-tiles/core-set-26-a.png",
    "side_b": "map-tiles/core-set-26-b.png"
  },
  {
    "id": "efcbd26b-a81e-4f8c-9e68-d992fd1c1bec",
    "name": "Core Set 27",
    "number": 27,
    "side_a": "map-tiles/core-set-27-a.png",
    "side_b": "map-tiles/core-set-27-b.png"
  },
  {
    "id": "be5f8edf-eaf8-45ef-9c7f-53a1c95bcf64",
    "name": "Core Set 28",
    "number": 28,
    "side_a": "map-tiles/core-set-28-a.png",
    "side_b": "map-tiles/core-set-28-b.png"
  },
  {
    "id": "e2a809f5-bad9-4fa3-92c5-9e264af2ed9b",
    "name": "Core Set 29",
    "number": 29,
    "side_a": "map-tiles/core-set-29-a.png",
    "side_b": "map-tiles/core-set-29-b.png"
  },
  {
    "id": "061d6a1a-a15f-4dd1-ad3b-3fa6d83114a1",
    "name": "Core Set 30",
    "number": 30,
    "side_a": "map-tiles/core-set-30-a.png",
    "side_b": "map-tiles/core-set-30-b.png"
  },
  {
    "id": "d5a04a02-2aa8-4ac7-9a4d-6c79e9f74b3e",
    "name": "Core Set 31",
    "number": 31,
    "side_a": "map-tiles/core-set-31-a.png",
    "side_b": "map-tiles/core-set-31-b.png"
  },
  {
    "id": "6b19495e-e0bd-4ce3-9048-d45b4771db2b",
    "name": "Core Set 32",
    "number": 32,
    "side_a": "map-tiles/core-set-32-a.png",
    "side_b": "map-tiles/core-set-32-b.png"
  },
  {
    "id": "b22328e9-59f3-4063-a741-8009aed5a57f",
    "name": "Core Set 33",
    "number": 33,
    "side_a": "map-tiles/core-set-33-a.png",
    "side_b": "map-tiles/core-set-33-b.png"
  },
  {
    "id": "629f199b-a9dc-4317-aad9-68ea21dd9ba7",
    "name": "Core Set 34",
    "number": 34,
    "side_a": "map-tiles/core-set-34-a.png",
    "side_b": "map-tiles/core-set-34-b.png"
  },
  {
    "id": "dbc60d7c-8bd2-4294-81dc-7ea51c61663a",
    "name": "Core Set 35",
    "number": 35,
    "side_a": "map-tiles/core-set-35-a.png",
    "side_b": "map-tiles/core-set-35-b.png"
  },
  {
    "id": "e2ff406c-389f-4790-b4ed-47c1bb561169",
    "name": "Core Set 36",
    "number": 36,
    "side_a": "map-tiles/core-set-36-a.png",
    "side_b": "map-tiles/core-set-36-b.png"
  },
  {
    "id": "de2f8b61-19bd-4ec9-a90d-86f0ac98ea3f",
    "name": "Core Set 37",
    "number": 37,
    "side_a": "map-tiles/core-set-37-a.png",
    "side_b": "map-tiles/core-set-37-b.png"
  },
  {
    "id": "c2deee54-68c7-499d-bed2-91bc82c39da6",
    "name": "Core Set 38",
    "number": 38,
    "side_a": "map-tiles/core-set-38-a.png",
    "side_b": "map-tiles/core-set-38-b.png"
  },
  {
    "id": "d4aa1428-50ff-47ed-ad46-fb062080d154",
    "name": "Core Set 39",
    "number": 39,
    "side_a": "map-tiles/core-set-39-a.png",
    "side_b": "map-tiles/core-set-39-b.png"
  },
  {
    "id": "46957916-1b86-4efd-a0a9-cc5f194b0c1d",
    "name": "Twin Shadows 01",
    "number": 1,
    "side_a": "map-tiles/twin-shadows-01-a.png",
    "side_b": "map-tiles/twin-shadows-01-b.png"
  },
  {
    "id": "c4587e2a-cb4a-42fd-a8fc-d601a38e498b",
    "name": "Twin Shadows 02",
    "number": 2,
    "side_a": "map-tiles/twin-shadows-02-a.png",
    "side_b": "map-tiles/twin-shadows-02-b.png"
  },
  {
    "id": "a21494be-8b58-42f8-8a8e-512bc5f1d453",
    "name": "Twin Shadows 03",
    "number": 3,
    "side_a": "map-tiles/twin-shadows-03-a.png",
    "side_b": "map-tiles/twin-shadows-03-b.png"
  },
  {
    "id": "8a9ad3e3-51a5-4b4e-b763-d2d3d18d07e1",
    "name": "Twin Shadows 04",
    "number": 4,
    "side_a": "map-tiles/twin-shadows-04-a.png",
    "side_b": "map-tiles/twin-shadows-04-b.png"
  },
  {
    "id": "2dfc8a44-6e42-47c4-993b-9457da63b04b",
    "name": "Twin Shadows 05",
    "number": 5,
    "side_a": "map-tiles/twin-shadows-05-a.png",
    "side_b": "map-tiles/twin-shadows-05-b.png"
  },
  {
    "id": "e6c646c7-32f3-410c-bba5-5a48582b5539",
    "name": "Twin Shadows 06",
    "number": 6,
    "side_a": "map-tiles/twin-shadows-06-a.png",
    "side_b": "map-tiles/twin-shadows-06-b.png"
  },
  {
    "id": "df6796e2-fb74-464b-8dc7-da822de21cab",
    "name": "Twin Shadows 07",
    "number": 7,
    "side_a": "map-tiles/twin-shadows-07-a.png",
    "side_b": "map-tiles/twin-shadows-07-b.png"
  },
  {
    "id": "a90dfd9c-a230-4322-82e0-f38c3825b5a7",
    "name": "Twin Shadows 08",
    "number": 8,
    "side_a": "map-tiles/twin-shadows-08-a.png",
    "side_b": "map-tiles/twin-shadows-08-b.png"
  },
  {
    "id": "a9fec593-cbad-41f5-80ff-3d682bf9cf2b",
    "name": "Twin Shadows 09",
    "number": 9,
    "side_a": "map-tiles/twin-shadows-09-a.png",
    "side_b": "map-tiles/twin-shadows-09-b.png"
  },
  {
    "id": "d7528d38-9ca6-4c10-aefa-5b8d86a5d809",
    "name": "Twin Shadows 10",
    "number": 10,
    "side_a": "map-tiles/twin-shadows-10-a.png",
    "side_b": "map-tiles/twin-shadows-10-b.png"
  },
  {
    "id": "d63bcd4d-d438-4d00-866e-57b5fdc615cf",
    "name": "Twin Shadows 11",
    "number": 11,
    "side_a": "map-tiles/twin-shadows-11-a.png",
    "side_b": "map-tiles/twin-shadows-11-b.png"
  },
  {
    "id": "95e7705c-8f0b-4dd2-a5a9-a7e3a88353c8",
    "name": "Twin Shadows 12",
    "number": 12,
    "side_a": "map-tiles/twin-shadows-12-a.png",
    "side_b": "map-tiles/twin-shadows-12-b.png"
  },
  {
