=== lvisintini/imperial-assault-data/schemas/mission-rewards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "mission-rewards.json#",
  "title": "Schema for the mission rewards data file: what each mission gives (cards or credits)",
  "type": "object",
  "definitions": {},
  "properties": {
    "mission_id": {
      "description": "Foreign key to the mission in data/missions.json (the index).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "content_type": {
      "description": "The reward's collection, or null when the reward is credits.",
      "oneOf": [
        {
          "$ref": "definitions.json#/definitions/content_type"
        },
        {
          "type": "null"
        }
      ]
    },
    "content_id": {
      "description": "The reward's id in that collection, or null when the reward is credits.",
      "oneOf": [
        {
          "$ref": "definitions.json#/definitions/uuid"
        },
        {
          "type": "null"
        }
      ]
    },
    "credits": {
      "type": "boolean",
      "description": "Whether the reward is credits (no card)."
    },
    "choice": {
      "type": "boolean",
      "description": "Whether the reward is one of the mission's alternatives: of its rows with choice true, the player picks one. Rows with choice false are all received."
    }
  },
  "required": [
    "mission_id",
    "content_type",
    "content_id",
    "credits",
    "choice"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/mission-rewards.json
[
  {
    "mission_id": "e6ffec7f-5d9f-41b3-926b-fc6c0d9280b1",
    "content_type": "reward-cards",
    "content_id": "41ba0e27-0367-513c-87af-dff958baf256",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "e6ffec7f-5d9f-41b3-926b-fc6c0d9280b1",
    "content_type": "reward-cards",
    "content_id": "adc59f43-077f-5396-b1fb-68a9f1379d4d",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "c05c7f99-efcf-4a05-91ae-4749533bbe1a",
    "content_type": "reward-cards",
    "content_id": "ed04b492-4f22-565b-8217-c782878ea7e5",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "c05c7f99-efcf-4a05-91ae-4749533bbe1a",
    "content_type": "reward-cards",
    "content_id": "5c3d1cc1-1d65-5b63-9aba-3b4abdadca41",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "b3c65b93-13fd-4418-834d-a18205368769",
    "content_type": "reward-cards",
    "content_id": "4faba9d9-2a0b-5989-931b-5802778685cf",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "b3c65b93-13fd-4418-834d-a18205368769",
    "content_type": "reward-cards",
    "content_id": "f132b8e0-9a1e-5b9d-bd1c-8949fa51b6f0",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "d0a46825-1b65-4379-aaa4-f3b3ab02aa92",
    "content_type": "reward-cards",
    "content_id": "f10ebe3e-16d9-531d-b965-79104f3d1a25",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "d0a46825-1b65-4379-aaa4-f3b3ab02aa92",
    "content_type": "reward-cards",
    "content_id": "5472de3f-23e0-599f-8f55-2090f887c881",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "6a487f3a-8abd-4fc2-8bfa-360d9cc60f33",
    "content_type": "reward-cards",
    "content_id": "441368fb-d277-5004-b542-d4c69860a6e9",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "c573e018-0278-454b-84be-8b07c56d3a83",
    "content_type": "reward-cards",
    "content_id": "f0e5b86e-4dfc-5c05-99e6-bd4b33a86294",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "77602a5d-099c-4ba6-b4ee-08b35223498b",
    "content_type": "reward-cards",
    "content_id": "2842cc42-6870-5b86-97c2-fd7a7d550a38",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "11210c18-47c7-425e-8de2-3551489c0d27",
    "content_type": "reward-cards",
    "content_id": "d722bb31-6e1e-593f-8182-f5cd9c10bd20",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "e68da0d6-6377-41d7-aef3-28031a306b58",
    "content_type": "reward-cards",
    "content_id": "8c328237-1092-53fc-bb88-cc845b617aa1",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "5f0833ec-6eec-4ba5-a794-d55e8517c45b",
    "content_type": "reward-cards",
    "content_id": "58110173-948c-5cac-b843-df2d0f4d966f",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "61e6c8d8-3ce3-4d9e-85f1-c33b9cd97df3",
    "content_type": "reward-cards",
    "content_id": "9a0bb796-7c83-560b-8cfb-a41849584b80",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "1ff09905-39bc-454d-a966-c3fec80bc5f2",
    "content_type": "reward-cards",
    "content_id": "9a155cac-9b4c-56d4-8028-5b8aeab2e574",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "8ce5a2d1-ff74-453b-9c06-8115da81eada",
    "content_type": "reward-cards",
    "content_id": "212de08e-f967-5a3c-88da-b3a4d32091b2",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "d9953a40-80ff-4256-bad0-222997530e14",
    "content_type": "reward-cards",
    "content_id": "90cea9c1-f830-586e-abf4-b34f7af1e1b2",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "8b91bf70-fa95-46fb-9ea9-951c6bc39519",
    "content_type": "reward-cards",
    "content_id": "65f456d4-6a14-5fe0-af66-8962e667d691",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "6e4d0b85-98f2-409e-b164-1e64bf61373e",
    "content_type": "reward-cards",
    "content_id": "daa8f12c-b023-5ed1-b360-00b30c122760",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "453d67c4-a239-4356-8830-640fb4f00721",
    "content_type": "reward-cards",
    "content_id": "7220527b-563e-54ed-90ee-e6f1c2259511",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "70ca4a52-616c-4d9c-8bf4-54a9ed90d09d",
    "content_type": "reward-cards",
    "content_id": "b6ecc9cb-5e4e-5fa6-85fd-2f81ba919e06",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "e9abba49-b738-4285-8ffa-50b565c89373",
    "content_type": "reward-cards",
    "content_id": "fbf79395-cc1a-541e-890b-4afce0771eb8",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "e5278f83-a178-46d9-8580-a552a4e94616",
    "content_type": "reward-cards",
    "content_id": "2c26b9fe-0294-5546-b9ec-60504d417841",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "4d75834a-c7b3-419a-b825-b942d694fbc9",
    "content_type": "reward-cards",
    "content_id": "646896f8-92bc-5937-beb9-c98452442460",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "d3e52ef2-9623-465e-80ab-d41d8e079284",
    "content_type": "reward-cards",
    "content_id": "a7e8a228-26cc-53e2-8798-80668f4d7703",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "c107808b-c5fa-49f0-ba5f-aa0a47b8cf2f",
    "content_type": "reward-cards",
    "content_id": "de63a870-8cb9-56ce-a522-27d283ff588d",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "0ca37b11-9e06-4553-a21d-bf0d97b0bcff",
    "content_type": "reward-cards",
    "content_id": "bd9b0b82-0760-58f1-baf7-3ae9a30a435b",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "1b7f0f11-83f6-40df-bfa1-c80112e03b43",
    "content_type": "reward-cards",
    "content_id": "0db0bb2c-9d3c-5e40-93e7-cd21c378eb87",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "ef9f483a-f0b2-4344-8612-aac12cdbd7ba",
    "content_type": "deployment-cards",
    "content_id": "c1b43496-afea-5548-975a-f77963a761ef",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "d0c7914c-0afb-444c-a581-a4ad66499188",
    "content_type": "deployment-cards",
    "content_id": "ae9ce593-c113-5001-829d-c912baa7ac07",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "0ec54688-e050-47f4-be56-08fbfa942f7c",
    "content_type": "deployment-cards",
    "content_id": "c1b43496-afea-5548-975a-f77963a761ef",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "f574a9bf-1bcf-45e7-9d32-b5b81bea0d05",
    "content_type": "deployment-cards",
    "content_id": "ccdbb3f0-f0c2-5311-9eb1-276875574410",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "8fb8c376-b06f-421f-8575-6fdce9c901cb",
    "content_type": "deployment-cards",
    "content_id": "fe4c1348-e1d3-5459-8a40-5025298311e8",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "e8af024f-4e4b-4a0b-a22c-fff0441c70ff",
    "content_type": "deployment-cards",
    "content_id": "73ec1673-9207-5bec-a3d2-b46ebecc7d1f",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "b23b2b57-0c7c-5e8a-9af4-c74792c89e15",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "711cdb33-3a5d-5198-8b7a-3406c9bbf2cd",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "4e2fe0d0-5aa4-540d-9b38-7e9b30f5535b",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "f0f30c83-f5cd-5c9e-b58a-09f9d720ef0a",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "18d58ccf-14e1-516a-86f6-a38987bdc820",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "deployment-cards",
    "content_id": "0959b4d4-d924-55bb-9897-bc974403fa00",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "cbe86c2b-adf7-4744-b6f8-f6e8e80583a8",
    "content_type": "reward-cards",
    "content_id": "2b8bbc83-31f3-59a1-8aa6-b677a8248cd7",
    "credits": false,
    "choice": false
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "b23b2b57-0c7c-5e8a-9af4-c74792c89e15",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "711cdb33-3a5d-5198-8b7a-3406c9bbf2cd",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "4e2fe0d0-5aa4-540d-9b38-7e9b30f5535b",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "f0f30c83-f5cd-5c9e-b58a-09f9d720ef0a",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "18d58ccf-14e1-516a-86f6-a38987bdc820",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "deployment-cards",
    "content_id": "0959b4d4-d924-55bb-9897-bc974403fa00",
    "credits": false,
    "choice": true
  },
  {
    "mission_id": "db6d3b98-2ddf-4e73-b9e1-d05c15884d47",
    "content_type": "reward-cards",
    "content_id": "4c2308c6-ea30-5752-818e-1f31d90b2ad0",
    "credits": false,
