=== lvisintini/imperial-assault-data/schemas/missions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "missions.json#",
  "title": "Schema for the missions data file: an index of every mission, whichever collection its card is in",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "description": "Id for entry: a UUID (see docs/data-model.md).",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "content_type": {
      "description": "The collection the mission's card is in (agenda-cards: an agenda card that is a mission).",
      "enum": [
        "campaign-story-mission-cards",
        "campaign-threat-mission-cards",
        "campaign-hero-side-mission-cards",
        "campaign-ally-side-mission-cards",
        "campaign-regular-side-mission-cards",
        "agenda-cards",
        "skirmish-mission-cards"
      ]
    },
    "content_id": {
      "description": "The mission card's id in that collection.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "map_id": {
      "description": "Foreign key to the map in data/maps.json the mission is played on; null only when the dataset has no image of it (campaign maps, for now).",
      "oneOf": [
        {
          "$ref": "definitions.json#/definitions/uuid"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "id",
    "content_type",
    "content_id",
    "map_id"
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/missions.json
[
  {
    "id": "7bbdb159-e239-4ad5-8220-f129446c95b8",
    "content_type": "campaign-story-mission-cards",
    "content_id": "fc7f612f-31f6-5553-b2f8-6d4a10cdec0b",
    "map_id": null
  },
  {
    "id": "95f02d32-7840-4c5e-8270-334c494ce6a1",
    "content_type": "campaign-story-mission-cards",
    "content_id": "ca140189-7961-54d4-b1b7-bfc8e851ce79",
    "map_id": null
  },
  {
    "id": "abf5590d-d6dc-4c3e-bb47-9d70abba8931",
    "content_type": "campaign-story-mission-cards",
    "content_id": "c0e9884f-5105-5af2-ae15-9d0e87ac015f",
    "map_id": null
  },
  {
    "id": "9609464a-a6a5-4011-9ad6-fe7e8ce2c688",
    "content_type": "campaign-story-mission-cards",
    "content_id": "505d1d01-157a-573d-8796-bc6dcf69f5a8",
    "map_id": null
  },
  {
    "id": "052f2e35-f2f3-42fa-99f2-106ea280d673",
    "content_type": "campaign-story-mission-cards",
    "content_id": "4f4d1c31-2333-5e70-a4c7-15ba0f6085f6",
    "map_id": null
  },
  {
    "id": "c4d865b6-93af-49fd-90f2-06640e400094",
    "content_type": "campaign-story-mission-cards",
    "content_id": "764c7038-a0d7-559d-aa04-7f32a842e518",
    "map_id": null
  },
  {
    "id": "11787c2d-98df-4358-9c58-a7b57093a019",
    "content_type": "campaign-story-mission-cards",
    "content_id": "ff7455ac-5990-5fbb-a621-77e1dcc61125",
    "map_id": null
  },
  {
    "id": "21f1bf87-2fdc-45ca-a58c-98d944447a2d",
    "content_type": "campaign-story-mission-cards",
    "content_id": "f179602c-4a26-58c7-9d56-a00b321be3c2",
    "map_id": null
  },
  {
    "id": "0c8da711-f13e-4814-9cd0-72f0f078faa2",
    "content_type": "campaign-story-mission-cards",
    "content_id": "ac081d23-53c9-541d-92dc-48a04bd84be9",
    "map_id": null
  },
  {
    "id": "8a844cf0-178d-4318-8dea-3c808b3da6a5",
    "content_type": "campaign-story-mission-cards",
    "content_id": "406d6db5-4188-5774-8079-8932fafef5dc",
    "map_id": null
  },
  {
    "id": "33d36b6b-9790-458e-b26a-4c783708fa8e",
    "content_type": "campaign-story-mission-cards",
    "content_id": "0302d097-5954-5e79-831a-b966c579ea91",
    "map_id": null
  },
  {
    "id": "712cd606-f2e5-478b-b28e-fe6ae661ff2c",
    "content_type": "campaign-story-mission-cards",
    "content_id": "d8823fa9-28d5-587e-b082-6eef63381900",
    "map_id": null
  },
  {
    "id": "d9457d2f-218d-4de8-b33a-112a19fe6bc5",
    "content_type": "campaign-story-mission-cards",
    "content_id": "3e5f52c8-a651-5061-a088-7d6e8c8c85df",
    "map_id": null
  },
  {
    "id": "8334799f-5cfb-4a9f-aeb4-12473aa28309",
    "content_type": "campaign-story-mission-cards",
    "content_id": "cfc8ef72-404c-5c21-a6a5-1651d6f41961",
    "map_id": null
  },
  {
    "id": "46091fb9-7f74-4bfc-8007-55eeafaa97c9",
    "content_type": "campaign-story-mission-cards",
    "content_id": "02dcedea-7ff1-5542-ac44-a051bbf310a8",
    "map_id": null
  },
  {
    "id": "a7561017-80bd-4946-b910-1306b105cc5a",
    "content_type": "campaign-story-mission-cards",
    "content_id": "b2db846a-7d76-5816-aea1-368d5e9d519b",
    "map_id": null
  },
  {
    "id": "75250a9f-2bbe-48e6-b366-39fd1ad64a61",
    "content_type": "campaign-story-mission-cards",
    "content_id": "bd6b0551-f71e-593d-9095-f9cfb3000941",
    "map_id": null
  },
  {
    "id": "574532e8-552d-468e-8c79-8d3a17814cad",
    "content_type": "campaign-story-mission-cards",
    "content_id": "5026f5e9-c8ff-5de8-afe1-02d6a73db2a9",
    "map_id": null
  },
  {
    "id": "d29c34dc-7a96-44f7-8f69-73e649a55430",
    "content_type": "campaign-story-mission-cards",
    "content_id": "93cb831c-d6e7-59ba-a8b0-d0b7b7f2b6e2",
    "map_id": null
  },
  {
    "id": "d0c03f12-a342-4878-a45d-233ada0e3bcb",
    "content_type": "campaign-story-mission-cards",
    "content_id": "2f96b6ec-6b0b-50a1-baab-0a62c041d952",
    "map_id": null
  },
  {
    "id": "658e950b-58a6-49f2-9ab3-66b2919a213d",
    "content_type": "campaign-story-mission-cards",
    "content_id": "db1860c8-7832-5497-ab46-666ce9372762",
    "map_id": null
  },
  {
    "id": "a1dcd5e7-7c99-469f-88fe-d9fe8a0a6bf2",
    "content_type": "campaign-story-mission-cards",
    "content_id": "60a9a403-4373-5c2d-a3f5-3ba170299aca",
    "map_id": null
  },
  {
    "id": "73827034-7fa4-452d-90cf-fb158a401d46",
    "content_type": "campaign-story-mission-cards",
    "content_id": "be1144ec-9be7-5386-899f-ddac397b8f3d",
    "map_id": null
  },
  {
    "id": "b41cb7d0-1150-428f-b1a3-b6c65a36405e",
    "content_type": "campaign-story-mission-cards",
    "content_id": "8fbb3179-ce3c-57df-8179-afd76d8cb601",
    "map_id": null
  },
  {
    "id": "de06bfd8-097e-4ea7-9c71-80209a5adc69",
    "content_type": "campaign-story-mission-cards",
    "content_id": "eaef766b-6a3e-50d6-9d7c-0e3149f37d78",
    "map_id": null
  },
  {
    "id": "dae32182-88a7-462f-b26f-e2df55d6f909",
    "content_type": "campaign-story-mission-cards",
    "content_id": "7a297013-1c25-5127-808c-a925b0e59088",
    "map_id": null
  },
  {
    "id": "e36a8163-e36e-439f-bdf9-19a98202e25c",
    "content_type": "campaign-story-mission-cards",
    "content_id": "bb25a423-f800-5232-a3e1-1b551e599aaf",
    "map_id": null
  },
  {
    "id": "2a8f3460-2b8f-49aa-8e16-6ef82d41c5ad",
    "content_type": "campaign-story-mission-cards",
    "content_id": "e2c497ae-e255-5308-af15-1df8beebf811",
    "map_id": null
  },
  {
    "id": "657b740c-8415-4dbe-b4f1-293d91e01524",
    "content_type": "campaign-story-mission-cards",
    "content_id": "e0e0b002-7b79-5bac-8fa4-457d5a6fc334",
    "map_id": null
  },
  {
    "id": "64d9f82a-544a-4313-bbb0-4fcd00c5e00a",
    "content_type": "campaign-story-mission-cards",
    "content_id": "dcc07cea-ecdd-5e48-8e87-4230f0cf4d7f",
    "map_id": null
  },
  {
    "id": "51fd3068-b1f7-4a6a-b9bc-c2304f9aaaeb",
    "content_type": "campaign-story-mission-cards",
    "content_id": "916120f0-9c39-57b7-9e95-d21be781d9ff",
    "map_id": null
  },
  {
    "id": "96151a10-c58e-4bfe-a638-64f78f5ea3b3",
    "content_type": "campaign-story-mission-cards",
    "content_id": "ed74833a-e4da-5d59-9098-934b0bcb7c53",
    "map_id": null
  },
  {
    "id": "6e6fcb76-7735-4638-b323-35a1e4dad06a",
    "content_type": "campaign-story-mission-cards",
    "content_id": "48bbb394-89cf-5c61-8613-01b99d194dbf",
    "map_id": null
  },
  {
    "id": "8f5b471b-73cf-43e2-9276-8b21252807a4",
    "content_type": "campaign-story-mission-cards",
    "content_id": "673873cf-1919-549b-807b-af0800597c9c",
    "map_id": null
  },
  {
    "id": "b722091f-65d3-47e2-8681-fac679c3bbf1",
    "content_type": "campaign-story-mission-cards",
    "content_id": "c43b6962-fd67-5890-aedd-c0f92bd51247",
    "map_id": null
  },
  {
    "id": "d06f8a49-46b3-486b-9936-0706a103537e",
    "content_type": "campaign-story-mission-cards",
    "content_id": "d02db3c4-cc01-55ff-927e-b8be338eb9b9",
    "map_id": null
  },
  {
    "id": "491cd674-c44a-49c6-953b-6960154922b9",
    "content_type": "campaign-story-mission-cards",
    "content_id": "219304ae-96a1-5676-8a77-8a34bf3a55a7",
    "map_id": null
  },
  {
    "id": "34ce1330-1e5b-462a-ae73-b0b4371a31b9",
    "content_type": "campaign-story-mission-cards",
    "content_id": "50a9b1f7-6a99-5f1f-849e-7d726fd524b0",
    "map_id": null
  },
  {
    "id": "cf18d975-be3a-4254-93e9-9dda4802d8d2",
    "content_type": "campaign-story-mission-cards",
    "content_id": "d9a7025a-85af-55f4-a8f7-c400a02689a1",
    "map_id": null
  },
  {
    "id": "ba8841e9-aec9-48d2-88de-2d6c0b254285",
    "content_type": "campaign-story-mission-cards",
    "content_id": "4aa85336-e8fd-5355-928c-ee74ff7e3b9e",
    "map_id": null
  },
  {
    "id": "e6ffec7f-5d9f-41b3-926b-fc6c0d9280b1",
    "content_type": "campaign-threat-mission-cards",
    "content_id": "4fd9b597-812c-5ca3-9cf1-7da10dde873a",
    "map_id": null
  },
  {
    "id": "c05c7f99-efcf-4a05-91ae-4749533bbe1a",
    "content_type": "campaign-threat-mission-cards",
    "content_id": "c6faf287-3f47-58ba-878a-e2778a9d8222",
    "map_id": null
  },
  {
    "id": "b3c65b93-13fd-4418-834d-a18205368769",
    "content_type": "campaign-threat-mission-cards",
    "content_id": "9ed8be42-c8be-5214-87b1-68388e52a592",
    "map_id": null
  },
  {
    "id": "d0a46825-1b65-4379-aaa4-f3b3ab02aa92",
    "content_type": "campaign-threat-mission-cards",
    "content_id": "54dad23c-4409-51c2-bfac-e12dd38457e8",
    "map_id": null
  },
  {
    "id": "6a487f3a-8abd-4fc2-8bfa-360d9cc60f33",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "52da081e-525b-5f4d-9f60-4a8f4453b4c0",
    "map_id": null
  },
  {
    "id": "c573e018-0278-454b-84be-8b07c56d3a83",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "be3b644f-8f22-5743-b8ae-616228927225",
    "map_id": null
  },
  {
    "id": "77602a5d-099c-4ba6-b4ee-08b35223498b",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "350dbdcb-efe5-53de-be1f-f4b14cb432e5",
    "map_id": null
  },
  {
    "id": "11210c18-47c7-425e-8de2-3551489c0d27",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "91f62f69-da99-542a-b43c-bbbe99263288",
    "map_id": null
  },
  {
    "id": "e68da0d6-6377-41d7-aef3-28031a306b58",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "74aac00f-4ff3-578c-a684-25c97aa4d4f9",
    "map_id": null
  },
  {
    "id": "5f0833ec-6eec-4ba5-a794-d55e8517c45b",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "5838bfab-9c6c-594d-af8e-83409f899c61",
    "map_id": null
  },
  {
    "id": "61e6c8d8-3ce3-4d9e-85f1-c33b9cd97df3",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "af7e4575-e0ea-5e80-ad85-d3d2b1f67038",
    "map_id": null
  },
  {
    "id": "1ff09905-39bc-454d-a966-c3fec80bc5f2",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "a255c6cf-d742-5697-9d7c-1d70b8a01ef1",
    "map_id": null
  },
  {
    "id": "8ce5a2d1-ff74-453b-9c06-8115da81eada",
    "content_type": "campaign-hero-side-mission-cards",
    "content_id": "c8222a4b-3e88-5046-a8a1-68a57fc7c436",
