=== lvisintini/imperial-assault-data/schemas/record-links.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "record-links.json#",
  "title": "Schema for the record links data file: how two records of any types relate, read both ways (see docs/data-model.md)",
  "type": "object",
  "definitions": {},
  "properties": {
    "from_type": {
      "description": "The collection of the record the link is from.",
      "$ref": "definitions.json#/definitions/content_type"
    },
    "from_id": {
      "description": "The record's id in that collection.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "to_type": {
      "description": "The collection of the record the link is to.",
      "$ref": "definitions.json#/definitions/content_type"
    },
    "to_id": {
      "description": "The record's id in that collection.",
      "$ref": "definitions.json#/definitions/uuid"
    },
    "relation": {
      "description": "How the from record relates to the to record. figure-of: the miniature stands for the deployment card or hero. form-of: the form card is a form of the deployment card. elite-of: the elite deployment card is the elite version of the regular one. campaign-of: the Campaign-only deployment card is the campaign version of the Skirmish-only one. document-for: the document was published for the source (not in its box). requires: the record can only be played with the source. expands: the record adds to the source.",
      "enum": [
        "figure-of",
        "form-of",
        "elite-of",
        "campaign-of",
        "document-for",
        "requires",
        "expands"
      ]
    },
    "reverse_relation": {
      "description": "The same link read from the to record: has-figure, has-form, regular-of, skirmish-of, has-document, required-by, expanded-by.",
      "enum": [
        "has-figure",
        "has-form",
        "regular-of",
        "skirmish-of",
        "has-document",
        "required-by",
        "expanded-by"
      ]
    }
  },
  "required": [
    "from_type",
    "from_id",
    "to_type",
    "to_id",
    "relation",
    "reverse_relation"
  ],
  "oneOf": [
    {
      "description": "A miniature and the deployment cards and hero it stands for.",
      "properties": {
        "relation": {"enum": ["figure-of"]},
        "reverse_relation": {"enum": ["has-figure"]},
        "from_type": {"enum": ["miniatures"]},
        "to_type": {"enum": ["deployment-cards", "heroes"]}
      }
    },
    {
      "description": "A form card and the deployment cards it's a form of.",
      "properties": {
        "relation": {"enum": ["form-of"]},
        "reverse_relation": {"enum": ["has-form"]},
        "from_type": {"enum": ["form-cards"]},
        "to_type": {"enum": ["deployment-cards"]}
      }
    },
    {
      "description": "An elite deployment card and the regular card of the same name.",
      "properties": {
        "relation": {"enum": ["elite-of"]},
        "reverse_relation": {"enum": ["regular-of"]},
        "from_type": {"enum": ["deployment-cards"]},
        "to_type": {"enum": ["deployment-cards"]}
      }
    },
    {
      "description": "A Campaign-only deployment card and its Skirmish-only twin.",
      "properties": {
        "relation": {"enum": ["campaign-of"]},
        "reverse_relation": {"enum": ["skirmish-of"]},
        "from_type": {"enum": ["deployment-cards"]},
        "to_type": {"enum": ["deployment-cards"]}
      }
    },
    {
      "description": "A document published for a source, but not in its box.",
      "properties": {
        "relation": {"enum": ["document-for"]},
        "reverse_relation": {"enum": ["has-document"]},
        "from_type": {"enum": ["documents"]},
        "to_type": {"enum": ["sources"]}
      }
    },
    {
      "description": "A record (a product, a mission, ...) that can only be played with a source.",
      "properties": {
        "relation": {"enum": ["requires"]},
        "reverse_relation": {"enum": ["required-by"]},
        "to_type": {"enum": ["sources"]}
      }
    },
    {
      "description": "A record that adds to a source.",
      "properties": {
        "relation": {"enum": ["expands"]},
        "reverse_relation": {"enum": ["expanded-by"]},
        "to_type": {"enum": ["sources"]}
      }
    }
  ],
  "additionalProperties": false
}

=== lvisintini/imperial-assault-data/data/record-links.json
[
  {
    "from_type": "miniatures",
    "from_id": "5be6424d-042a-415d-a3eb-25937cbb0157",
    "to_type": "deployment-cards",
    "to_id": "f0fc2da5-6a0f-5073-b9bb-01f49eb93349",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "5be6424d-042a-415d-a3eb-25937cbb0157",
    "to_type": "heroes",
    "to_id": "3b88e344-6d87-55fa-8e3e-ebfaf9b0ec31",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "b4f678ba-d85a-41b9-a854-b55a5d2ab23c",
    "to_type": "deployment-cards",
    "to_id": "db5b3478-512a-5e56-9726-b0c17f428cc5",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "b4f678ba-d85a-41b9-a854-b55a5d2ab23c",
    "to_type": "heroes",
    "to_id": "f42d3b44-5e18-54a9-a8f5-38c78dac9723",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "f32eaa9b-c0e2-40eb-b527-383219b3fa22",
    "to_type": "deployment-cards",
    "to_id": "9ab864e6-2ab4-5a39-8937-f60ab01f75c3",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "f32eaa9b-c0e2-40eb-b527-383219b3fa22",
    "to_type": "heroes",
    "to_id": "289c0175-d8b4-5d26-b9de-27a62c7af1c2",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "4762a29b-5622-4054-a5f6-03030003eaa0",
    "to_type": "deployment-cards",
    "to_id": "d6c87c9e-1c69-509d-a651-3dd359e5824d",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "4762a29b-5622-4054-a5f6-03030003eaa0",
    "to_type": "heroes",
    "to_id": "703db9b7-9fac-5e46-98c1-402024692a92",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "ddd966d9-ed1e-47a4-9d48-1346eaf91365",
    "to_type": "deployment-cards",
    "to_id": "3e818577-c542-5d2d-a1ff-f5335a365c9c",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "ddd966d9-ed1e-47a4-9d48-1346eaf91365",
    "to_type": "heroes",
    "to_id": "b2f1c557-b491-5633-83ec-f0016e3f10f6",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "c33f8e75-3f47-4505-80cf-cfbde08efceb",
    "to_type": "deployment-cards",
    "to_id": "cfe4e96a-d1eb-5384-83ba-327fcfca1417",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "c33f8e75-3f47-4505-80cf-cfbde08efceb",
    "to_type": "heroes",
    "to_id": "59154ab5-6c82-5bbe-9d3c-b61ba1604bff",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "ff462496-8666-43db-a447-9b5354d6d347",
    "to_type": "deployment-cards",
    "to_id": "ae9ce593-c113-5001-829d-c912baa7ac07",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "eeb68e22-6fbd-41e7-9786-058d54687f67",
    "to_type": "deployment-cards",
    "to_id": "8ab9c881-2ea6-5e88-99df-40caac828a75",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "eeb68e22-6fbd-41e7-9786-058d54687f67",
    "to_type": "deployment-cards",
    "to_id": "901168b6-f1ae-564b-81d0-ad253f5e2e52",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "46b9b44c-3b08-4d2d-9aa2-9dd474394b0b",
    "to_type": "deployment-cards",
    "to_id": "9901e4e1-f2bf-556a-bc4d-6719be9f9055",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "46b9b44c-3b08-4d2d-9aa2-9dd474394b0b",
    "to_type": "deployment-cards",
    "to_id": "185b2837-1fe5-56b8-9e63-bbb99f22b211",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "02fa8d58-19a2-4ee2-af89-ae85c789ba73",
    "to_type": "deployment-cards",
    "to_id": "8694fbd4-0165-527e-aea4-a9dc48e46d87",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "02fa8d58-19a2-4ee2-af89-ae85c789ba73",
    "to_type": "deployment-cards",
    "to_id": "6caab715-26a5-532e-88ec-9ac22e9da08b",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "56eb8936-03fb-482e-a793-d141bc586996",
    "to_type": "deployment-cards",
    "to_id": "91139b33-3d62-5d51-bd87-f4d92b454bb0",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "56eb8936-03fb-482e-a793-d141bc586996",
    "to_type": "deployment-cards",
    "to_id": "30ab9d0c-12a2-5cfd-8039-b2ab168ab74c",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e4957520-5546-41c6-94be-c43273397ee1",
    "to_type": "deployment-cards",
    "to_id": "9188010f-9a86-549f-97b7-4d357d4687f4",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e4957520-5546-41c6-94be-c43273397ee1",
    "to_type": "deployment-cards",
    "to_id": "7217415c-c215-537c-9c98-23e120ed94b8",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "5ed665e5-b093-460b-98ff-bdca40dd8f0d",
    "to_type": "deployment-cards",
    "to_id": "f2a1c20b-ce85-5f1a-bb2b-c9b964b11d18",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e701eb5b-f904-4630-bc9c-231b6bd94faa",
    "to_type": "deployment-cards",
    "to_id": "487c2d05-aed5-508b-af2a-9132f846eedc",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "223c338b-8c06-4788-b3ed-fa0c55358dc7",
    "to_type": "deployment-cards",
    "to_id": "f7913b45-0a0f-5c01-8be1-711618f85cf2",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "223c338b-8c06-4788-b3ed-fa0c55358dc7",
    "to_type": "deployment-cards",
    "to_id": "6c654997-bff4-5b72-ab3e-51532b19dbb9",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "209189d3-e148-450c-a788-6884e9d6572a",
    "to_type": "deployment-cards",
    "to_id": "f4536050-3b54-5e93-8a93-6aa1bf460519",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "209189d3-e148-450c-a788-6884e9d6572a",
    "to_type": "deployment-cards",
    "to_id": "0ea2e2a5-0f1c-5ae3-b316-b1628832858c",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e1c769ac-6b4e-497a-9652-cc2d71ef139d",
    "to_type": "deployment-cards",
    "to_id": "fe4c1348-e1d3-5459-8a40-5025298311e8",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "f4615b81-d923-40a1-b99a-662927da8d5f",
    "to_type": "deployment-cards",
    "to_id": "c1b43496-afea-5548-975a-f77963a761ef",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e58e43a0-6f69-4f3c-b9d8-18cca794b448",
    "to_type": "deployment-cards",
    "to_id": "79a638ad-5b9d-5a31-bdc6-c0384c86f264",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "e58e43a0-6f69-4f3c-b9d8-18cca794b448",
    "to_type": "deployment-cards",
    "to_id": "5c084571-957a-5245-8940-2c473798db90",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "b97b4294-577d-4c9e-aef6-dcf848c8920e",
    "to_type": "deployment-cards",
    "to_id": "ccdbb3f0-f0c2-5311-9eb1-276875574410",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "b97b4294-577d-4c9e-aef6-dcf848c8920e",
    "to_type": "deployment-cards",
    "to_id": "c7c2ce4f-ce5f-5cd0-b0ae-8cbfe8ff9c03",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "84bb56c3-a4ca-4ef3-9d46-a5a2ae19f367",
    "to_type": "deployment-cards",
    "to_id": "06498bf6-c2f7-568e-b008-e2a79523b4e3",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "8f11b160-69b3-4c30-a514-f3e7ee9330b5",
    "to_type": "deployment-cards",
    "to_id": "439490d4-98da-536a-90e6-a399faa70aaf",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "8f11b160-69b3-4c30-a514-f3e7ee9330b5",
    "to_type": "deployment-cards",
    "to_id": "f2a1c20b-ce85-5f1a-bb2b-c9b964b11d18",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "d21736a3-69a1-4ef9-8a70-0df9e9a23331",
    "to_type": "deployment-cards",
    "to_id": "fbc2b270-b325-524a-b6bc-2d5e92ec2222",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "9f577d77-0ca6-47bc-a1e7-98267c51d2c6",
    "to_type": "deployment-cards",
    "to_id": "c1ec5eeb-e148-5f99-a6a5-88fe3ef6280c",
    "relation": "figure-of",
    "reverse_relation": "has-figure"
  },
  {
    "from_type": "miniatures",
    "from_id": "9f577d77-0ca6-47bc-a1e7-98267c51d2c6",
